# docker-compose.yml here not used
version: '3.9'

services:
  app:
    image: node
    container_name: task_decodeup
    working_dir: "/usr/src/app"
    volumes:
      - ./:/usr/src/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - DB_URL=${DB_URL:-mongodb+srv://nikhildb:Nikhil@21@cluster1.kpemw.mongodb.net/tech_decodeup}
      # ... other environment variables ...
    command: >
      sh -c "npm install && npm run dev"
