version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:15 # Use Node.js 19 Docker image
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build the Application
          command: npm run dev

  # deploy:
  #   docker:
  #     - image: circleci/node:15  # Node.js Docker image for deployment
  #   steps:
  #     - checkout
  #     - run:
  #         name: Install SSH and rsync
  #         command: |
  #           sudo apt-get update
  #           sudo apt-get install -y rsync openssh-client
  #     - run:
  #         name: Deploy to EC2 (multiple apps)
  #         command: |
  #           # Sync files to the EC2 instance (replace with actual path)
  #           rsync -avz --delete ./dist/ ec2-user@<YOUR_PUBLIC_IP>:/path/to/your/app/

  #           # SSH into EC2 and restart applications with PM2 by name
  #           ssh ec2-user@<YOUR_PUBLIC_IP> "pm2 restart app1"
  #           ssh ec2-user@<YOUR_PUBLIC_IP> "pm2 restart app2"
  #           ssh ec2-user@<YOUR_PUBLIC_IP> "pm2 restart app3"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
